-- REGION: Types
create type "public"."tournament_level" as enum ('Test', 'Practice', 'Qualification', 'Playoff');

-- REGION: Sequences
create sequence "public"."levels_id_seq";

create sequence "public"."seasons_id_seq";

create sequence "public"."truck_routes_id_seq";

-- REGION: Tables
create table "public"."alliances" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid not null,
    "name" text not null,
    "team_numbers" integer[]
);

alter table "public"."alliances" enable row level security;


create table "public"."equipment" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "equipment_type_id" bigint not null,
    "teamviewer_id" text,
    "slack_user_id" text,
    "truck_route_id" integer,
    "configuration" jsonb
);

alter table "public"."equipment" enable row level security;


create table "public"."equipment_notes" (
    "id" bigint generated by default as identity not null,
    "equipment_id" bigint not null,
    "content" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null
);

alter table "public"."equipment_notes" enable row level security;


create table "public"."equipment_types" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);

alter table "public"."equipment_types" enable row level security;


create table "public"."event_notes" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid not null,
    "content" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null
);

alter table "public"."event_notes" enable row level security;


create table "public"."event_staffs" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid not null,
    "user_id" uuid not null
);

alter table "public"."event_staffs" enable row level security;


create table "public"."events" (
    "id" uuid not null default uuid_generate_v4(),
    "season_id" integer not null,
    "key" character varying(10) not null,
    "code" text,
    "sync_source" text,
    "is_official" boolean not null default false,
    "truck_route_id" integer,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "sync_as_of" timestamp with time zone,
    "status" character varying not null default 'NotStarted'::character varying
);

alter table "public"."events" enable row level security;


create table "public"."levels" (
    "id" integer not null default nextval('levels_id_seq'::regclass),
    "name" text not null
);

alter table "public"."levels" enable row level security;


create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid not null,
    "tournament_level" tournament_level not null,
    "match_number" integer not null,
    "play_number" integer,
    "red_alliance_teams" integer[],
    "blue_alliance_teams" integer[],
    "red_alliance_id" bigint,
    "blue_alliance_id" bigint,
    "scheduled_start_time" timestamp with time zone,
    "actual_start_time" timestamp with time zone,
    "post_result_time" timestamp with time zone,
    "is_discarded" boolean not null default false
);

alter table "public"."matches" enable row level security;


create table "public"."schedule_deviations" (
    "id" bigint generated by default as identity not null,
    "event_id" uuid not null,
    "description" text,
    "after_match_id" bigint not null,
    "associated_match_id" bigint
);

alter table "public"."schedule_deviations" enable row level security;


create table "public"."seasons" (
    "id" integer not null default nextval('seasons_id_seq'::regclass),
    "level_id" integer not null,
    "name" text not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null
);

alter table "public"."seasons" enable row level security;


create table "public"."truck_routes" (
    "id" integer not null default nextval('truck_routes_id_seq'::regclass),
    "name" text not null,
    "event_slack_channel_id" text
);

alter table "public"."truck_routes" enable row level security;

-- REGION: Sequences
alter sequence "public"."levels_id_seq" owned by "public"."levels"."id";

alter sequence "public"."seasons_id_seq" owned by "public"."seasons"."id";

alter sequence "public"."truck_routes_id_seq" owned by "public"."truck_routes"."id";

-- REGION: Indexes
CREATE UNIQUE INDEX alliances_pkey ON public.alliances USING btree (id);

CREATE UNIQUE INDEX equipment_notes_pkey ON public.equipment_notes USING btree (id);

CREATE UNIQUE INDEX equipment_pkey ON public.equipment USING btree (id);

CREATE UNIQUE INDEX equipment_types_name_key ON public.equipment_types USING btree (name);

CREATE UNIQUE INDEX equipment_types_pkey ON public.equipment_types USING btree (id);

CREATE UNIQUE INDEX event_notes_pkey ON public.event_notes USING btree (id);

CREATE UNIQUE INDEX event_staffs_pkey ON public.event_staffs USING btree (id);

CREATE UNIQUE INDEX events_key_uniq ON public.events USING btree (key);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX levels_name_uniq ON public.levels USING btree (name);

CREATE UNIQUE INDEX levels_pkey ON public.levels USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX schedule_deviations_pkey ON public.schedule_deviations USING btree (id);

CREATE UNIQUE INDEX seasons_level_name_uniq ON public.seasons USING btree (level_id, name);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

CREATE UNIQUE INDEX truck_routes_name_uniq ON public.truck_routes USING btree (name);

CREATE UNIQUE INDEX truck_routes_pkey ON public.truck_routes USING btree (id);

-- REGION: Constraints
alter table "public"."alliances" add constraint "alliances_pkey" PRIMARY KEY using index "alliances_pkey";

alter table "public"."equipment" add constraint "equipment_pkey" PRIMARY KEY using index "equipment_pkey";

alter table "public"."equipment_notes" add constraint "equipment_notes_pkey" PRIMARY KEY using index "equipment_notes_pkey";

alter table "public"."equipment_types" add constraint "equipment_types_pkey" PRIMARY KEY using index "equipment_types_pkey";

alter table "public"."event_notes" add constraint "event_notes_pkey" PRIMARY KEY using index "event_notes_pkey";

alter table "public"."event_staffs" add constraint "event_staffs_pkey" PRIMARY KEY using index "event_staffs_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."levels" add constraint "levels_pkey" PRIMARY KEY using index "levels_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."schedule_deviations" add constraint "schedule_deviations_pkey" PRIMARY KEY using index "schedule_deviations_pkey";

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."truck_routes" add constraint "truck_routes_pkey" PRIMARY KEY using index "truck_routes_pkey";

alter table "public"."alliances" add constraint "public_alliances_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."alliances" validate constraint "public_alliances_event_id_fkey";

alter table "public"."equipment" add constraint "public_equipment_equipment_type_id_fkey" FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."equipment" validate constraint "public_equipment_equipment_type_id_fkey";

alter table "public"."equipment" add constraint "public_equipment_truck_route_id_fkey" FOREIGN KEY (truck_route_id) REFERENCES truck_routes(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."equipment" validate constraint "public_equipment_truck_route_id_fkey";

alter table "public"."equipment_notes" add constraint "public_equipment_notes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."equipment_notes" validate constraint "public_equipment_notes_created_by_fkey";

alter table "public"."equipment_notes" add constraint "public_equipment_notes_equipment_id_fkey" FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."equipment_notes" validate constraint "public_equipment_notes_equipment_id_fkey";

alter table "public"."equipment_types" add constraint "equipment_types_name_key" UNIQUE using index "equipment_types_name_key";

alter table "public"."event_notes" add constraint "public_event_notes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."event_notes" validate constraint "public_event_notes_created_by_fkey";

alter table "public"."event_notes" add constraint "public_event_notes_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."event_notes" validate constraint "public_event_notes_event_id_fkey";

alter table "public"."event_staffs" add constraint "public_event_staffs_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_staffs" validate constraint "public_event_staffs_event_id_fkey";

alter table "public"."event_staffs" add constraint "public_event_staffs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."event_staffs" validate constraint "public_event_staffs_user_id_fkey";

alter table "public"."events" add constraint "events_check" CHECK ((start_time < end_time)) not valid;

alter table "public"."events" validate constraint "events_check";

alter table "public"."events" add constraint "events_check1" CHECK ((start_time < end_time)) not valid;

alter table "public"."events" validate constraint "events_check1";

alter table "public"."events" add constraint "events_season_id_fkey" FOREIGN KEY (season_id) REFERENCES seasons(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_season_id_fkey";

alter table "public"."events" add constraint "events_truck_route_id_fkey" FOREIGN KEY (truck_route_id) REFERENCES truck_routes(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_truck_route_id_fkey";

alter table "public"."matches" add constraint "public_matches_blue_alliance_id_fkey" FOREIGN KEY (blue_alliance_id) REFERENCES alliances(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."matches" validate constraint "public_matches_blue_alliance_id_fkey";

alter table "public"."matches" add constraint "public_matches_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "public_matches_event_id_fkey";

alter table "public"."matches" add constraint "public_matches_red_alliance_id_fkey" FOREIGN KEY (red_alliance_id) REFERENCES alliances(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."matches" validate constraint "public_matches_red_alliance_id_fkey";

alter table "public"."schedule_deviations" add constraint "public_schedule_deviations_after_match_id_fkey" FOREIGN KEY (after_match_id) REFERENCES matches(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."schedule_deviations" validate constraint "public_schedule_deviations_after_match_id_fkey";

alter table "public"."schedule_deviations" add constraint "public_schedule_deviations_associated_match_id_fkey" FOREIGN KEY (associated_match_id) REFERENCES matches(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."schedule_deviations" validate constraint "public_schedule_deviations_associated_match_id_fkey";

alter table "public"."schedule_deviations" add constraint "public_schedule_deviations_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."schedule_deviations" validate constraint "public_schedule_deviations_event_id_fkey";

alter table "public"."seasons" add constraint "seasons_level_id_fkey" FOREIGN KEY (level_id) REFERENCES levels(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."seasons" validate constraint "seasons_level_id_fkey";

-- REGION: Permissions
grant delete on table "public"."alliances" to "anon";

grant insert on table "public"."alliances" to "anon";

grant references on table "public"."alliances" to "anon";

grant select on table "public"."alliances" to "anon";

grant trigger on table "public"."alliances" to "anon";

grant truncate on table "public"."alliances" to "anon";

grant update on table "public"."alliances" to "anon";

grant delete on table "public"."alliances" to "authenticated";

grant insert on table "public"."alliances" to "authenticated";

grant references on table "public"."alliances" to "authenticated";

grant select on table "public"."alliances" to "authenticated";

grant trigger on table "public"."alliances" to "authenticated";

grant truncate on table "public"."alliances" to "authenticated";

grant update on table "public"."alliances" to "authenticated";

grant delete on table "public"."alliances" to "service_role";

grant insert on table "public"."alliances" to "service_role";

grant references on table "public"."alliances" to "service_role";

grant select on table "public"."alliances" to "service_role";

grant trigger on table "public"."alliances" to "service_role";

grant truncate on table "public"."alliances" to "service_role";

grant update on table "public"."alliances" to "service_role";

grant delete on table "public"."equipment" to "anon";

grant insert on table "public"."equipment" to "anon";

grant references on table "public"."equipment" to "anon";

grant select on table "public"."equipment" to "anon";

grant trigger on table "public"."equipment" to "anon";

grant truncate on table "public"."equipment" to "anon";

grant update on table "public"."equipment" to "anon";

grant delete on table "public"."equipment" to "authenticated";

grant insert on table "public"."equipment" to "authenticated";

grant references on table "public"."equipment" to "authenticated";

grant select on table "public"."equipment" to "authenticated";

grant trigger on table "public"."equipment" to "authenticated";

grant truncate on table "public"."equipment" to "authenticated";

grant update on table "public"."equipment" to "authenticated";

grant delete on table "public"."equipment" to "service_role";

grant insert on table "public"."equipment" to "service_role";

grant references on table "public"."equipment" to "service_role";

grant select on table "public"."equipment" to "service_role";

grant trigger on table "public"."equipment" to "service_role";

grant truncate on table "public"."equipment" to "service_role";

grant update on table "public"."equipment" to "service_role";

grant delete on table "public"."equipment_notes" to "anon";

grant insert on table "public"."equipment_notes" to "anon";

grant references on table "public"."equipment_notes" to "anon";

grant select on table "public"."equipment_notes" to "anon";

grant trigger on table "public"."equipment_notes" to "anon";

grant truncate on table "public"."equipment_notes" to "anon";

grant update on table "public"."equipment_notes" to "anon";

grant delete on table "public"."equipment_notes" to "authenticated";

grant insert on table "public"."equipment_notes" to "authenticated";

grant references on table "public"."equipment_notes" to "authenticated";

grant select on table "public"."equipment_notes" to "authenticated";

grant trigger on table "public"."equipment_notes" to "authenticated";

grant truncate on table "public"."equipment_notes" to "authenticated";

grant update on table "public"."equipment_notes" to "authenticated";

grant delete on table "public"."equipment_notes" to "service_role";

grant insert on table "public"."equipment_notes" to "service_role";

grant references on table "public"."equipment_notes" to "service_role";

grant select on table "public"."equipment_notes" to "service_role";

grant trigger on table "public"."equipment_notes" to "service_role";

grant truncate on table "public"."equipment_notes" to "service_role";

grant update on table "public"."equipment_notes" to "service_role";

grant delete on table "public"."equipment_types" to "anon";

grant insert on table "public"."equipment_types" to "anon";

grant references on table "public"."equipment_types" to "anon";

grant select on table "public"."equipment_types" to "anon";

grant trigger on table "public"."equipment_types" to "anon";

grant truncate on table "public"."equipment_types" to "anon";

grant update on table "public"."equipment_types" to "anon";

grant delete on table "public"."equipment_types" to "authenticated";

grant insert on table "public"."equipment_types" to "authenticated";

grant references on table "public"."equipment_types" to "authenticated";

grant select on table "public"."equipment_types" to "authenticated";

grant trigger on table "public"."equipment_types" to "authenticated";

grant truncate on table "public"."equipment_types" to "authenticated";

grant update on table "public"."equipment_types" to "authenticated";

grant delete on table "public"."equipment_types" to "service_role";

grant insert on table "public"."equipment_types" to "service_role";

grant references on table "public"."equipment_types" to "service_role";

grant select on table "public"."equipment_types" to "service_role";

grant trigger on table "public"."equipment_types" to "service_role";

grant truncate on table "public"."equipment_types" to "service_role";

grant update on table "public"."equipment_types" to "service_role";

grant delete on table "public"."event_notes" to "anon";

grant insert on table "public"."event_notes" to "anon";

grant references on table "public"."event_notes" to "anon";

grant select on table "public"."event_notes" to "anon";

grant trigger on table "public"."event_notes" to "anon";

grant truncate on table "public"."event_notes" to "anon";

grant update on table "public"."event_notes" to "anon";

grant delete on table "public"."event_notes" to "authenticated";

grant insert on table "public"."event_notes" to "authenticated";

grant references on table "public"."event_notes" to "authenticated";

grant select on table "public"."event_notes" to "authenticated";

grant trigger on table "public"."event_notes" to "authenticated";

grant truncate on table "public"."event_notes" to "authenticated";

grant update on table "public"."event_notes" to "authenticated";

grant delete on table "public"."event_notes" to "service_role";

grant insert on table "public"."event_notes" to "service_role";

grant references on table "public"."event_notes" to "service_role";

grant select on table "public"."event_notes" to "service_role";

grant trigger on table "public"."event_notes" to "service_role";

grant truncate on table "public"."event_notes" to "service_role";

grant update on table "public"."event_notes" to "service_role";

grant delete on table "public"."event_staffs" to "anon";

grant insert on table "public"."event_staffs" to "anon";

grant references on table "public"."event_staffs" to "anon";

grant select on table "public"."event_staffs" to "anon";

grant trigger on table "public"."event_staffs" to "anon";

grant truncate on table "public"."event_staffs" to "anon";

grant update on table "public"."event_staffs" to "anon";

grant delete on table "public"."event_staffs" to "authenticated";

grant insert on table "public"."event_staffs" to "authenticated";

grant references on table "public"."event_staffs" to "authenticated";

grant select on table "public"."event_staffs" to "authenticated";

grant trigger on table "public"."event_staffs" to "authenticated";

grant truncate on table "public"."event_staffs" to "authenticated";

grant update on table "public"."event_staffs" to "authenticated";

grant delete on table "public"."event_staffs" to "service_role";

grant insert on table "public"."event_staffs" to "service_role";

grant references on table "public"."event_staffs" to "service_role";

grant select on table "public"."event_staffs" to "service_role";

grant trigger on table "public"."event_staffs" to "service_role";

grant truncate on table "public"."event_staffs" to "service_role";

grant update on table "public"."event_staffs" to "service_role";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."levels" to "anon";

grant insert on table "public"."levels" to "anon";

grant references on table "public"."levels" to "anon";

grant select on table "public"."levels" to "anon";

grant trigger on table "public"."levels" to "anon";

grant truncate on table "public"."levels" to "anon";

grant update on table "public"."levels" to "anon";

grant delete on table "public"."levels" to "authenticated";

grant insert on table "public"."levels" to "authenticated";

grant references on table "public"."levels" to "authenticated";

grant select on table "public"."levels" to "authenticated";

grant trigger on table "public"."levels" to "authenticated";

grant truncate on table "public"."levels" to "authenticated";

grant update on table "public"."levels" to "authenticated";

grant delete on table "public"."levels" to "service_role";

grant insert on table "public"."levels" to "service_role";

grant references on table "public"."levels" to "service_role";

grant select on table "public"."levels" to "service_role";

grant trigger on table "public"."levels" to "service_role";

grant truncate on table "public"."levels" to "service_role";

grant update on table "public"."levels" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."schedule_deviations" to "anon";

grant insert on table "public"."schedule_deviations" to "anon";

grant references on table "public"."schedule_deviations" to "anon";

grant select on table "public"."schedule_deviations" to "anon";

grant trigger on table "public"."schedule_deviations" to "anon";

grant truncate on table "public"."schedule_deviations" to "anon";

grant update on table "public"."schedule_deviations" to "anon";

grant delete on table "public"."schedule_deviations" to "authenticated";

grant insert on table "public"."schedule_deviations" to "authenticated";

grant references on table "public"."schedule_deviations" to "authenticated";

grant select on table "public"."schedule_deviations" to "authenticated";

grant trigger on table "public"."schedule_deviations" to "authenticated";

grant truncate on table "public"."schedule_deviations" to "authenticated";

grant update on table "public"."schedule_deviations" to "authenticated";

grant delete on table "public"."schedule_deviations" to "service_role";

grant insert on table "public"."schedule_deviations" to "service_role";

grant references on table "public"."schedule_deviations" to "service_role";

grant select on table "public"."schedule_deviations" to "service_role";

grant trigger on table "public"."schedule_deviations" to "service_role";

grant truncate on table "public"."schedule_deviations" to "service_role";

grant update on table "public"."schedule_deviations" to "service_role";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";

grant delete on table "public"."truck_routes" to "anon";

grant insert on table "public"."truck_routes" to "anon";

grant references on table "public"."truck_routes" to "anon";

grant select on table "public"."truck_routes" to "anon";

grant trigger on table "public"."truck_routes" to "anon";

grant truncate on table "public"."truck_routes" to "anon";

grant update on table "public"."truck_routes" to "anon";

grant delete on table "public"."truck_routes" to "authenticated";

grant insert on table "public"."truck_routes" to "authenticated";

grant references on table "public"."truck_routes" to "authenticated";

grant select on table "public"."truck_routes" to "authenticated";

grant trigger on table "public"."truck_routes" to "authenticated";

grant truncate on table "public"."truck_routes" to "authenticated";

grant update on table "public"."truck_routes" to "authenticated";

grant delete on table "public"."truck_routes" to "service_role";

grant insert on table "public"."truck_routes" to "service_role";

grant references on table "public"."truck_routes" to "service_role";

grant select on table "public"."truck_routes" to "service_role";

grant trigger on table "public"."truck_routes" to "service_role";

grant truncate on table "public"."truck_routes" to "service_role";

grant update on table "public"."truck_routes" to "service_role";

-- REGION: RLS Policies
create policy "Enable read access for all users"
on "public"."levels"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."seasons"
as permissive
for select
to public
using (true);
